// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/bridge/message_set.proto
// Protobuf C++ Version: 5.28.0-dev

#include "google/protobuf/bridge/message_set.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace google {
namespace protobuf {
namespace bridge {

inline constexpr MessageSet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MessageSet::MessageSet(::_pbi::ConstantInitialized)
    : ::google::protobuf::Message(_class_data_.base()),
      _impl_(::_pbi::ConstantInitialized()) {}
struct MessageSetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageSetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageSetDefaultTypeInternal() {}
  union {
    MessageSet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageSetDefaultTypeInternal _MessageSet_default_instance_;
}  // namespace bridge
}  // namespace protobuf
}  // namespace google
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto = nullptr;
const ::uint32_t
    TableStruct_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::google::protobuf::bridge::MessageSet, _internal_metadata_),
        PROTOBUF_FIELD_OFFSET(::google::protobuf::bridge::MessageSet, _impl_._extensions_),
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::google::protobuf::bridge::MessageSet)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::google::protobuf::bridge::_MessageSet_default_instance_._instance,
};
const char descriptor_table_protodef_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n(google/protobuf/bridge/message_set.pro"
    "to\022\026google.protobuf.bridge\"\032\n\nMessageSet"
    "*\010\010\004\020\377\377\377\377\007:\002\010\001B\035B\020MessageSetProtosP\001\370\001\001\242"
    "\002\003GPB"
};
static ::absl::once_flag descriptor_table_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto = {
    false,
    false,
    125,
    descriptor_table_protodef_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto,
    "google/protobuf/bridge/message_set.proto",
    &descriptor_table_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto::offsets,
    file_level_enum_descriptors_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto,
    file_level_service_descriptors_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto,
};
namespace google {
namespace protobuf {
namespace bridge {
// ===================================================================

class MessageSet::_Internal {
 public:
};

MessageSet::MessageSet(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.protobuf.bridge.MessageSet)
}
inline PROTOBUF_NDEBUG_INLINE MessageSet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::google::protobuf::bridge::MessageSet& from_msg)
      : _extensions_{visibility, arena},
        _cached_size_{0} {}

MessageSet::MessageSet(
    ::google::protobuf::Arena* arena,
    const MessageSet& from)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
  MessageSet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);

  // @@protoc_insertion_point(copy_constructor:google.protobuf.bridge.MessageSet)
}
inline PROTOBUF_NDEBUG_INLINE MessageSet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _extensions_{visibility, arena},
        _cached_size_{0} {}

inline void MessageSet::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MessageSet::~MessageSet() {
  // @@protoc_insertion_point(destructor:google.protobuf.bridge.MessageSet)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MessageSet::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    MessageSet::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            MessageSet::IsInitializedImpl,
            &MessageSet::MergeImpl,
            ::google::protobuf::Message::GetDeleteImpl<MessageSet>(),
            ::google::protobuf::Message::GetNewImpl<MessageSet>(),
            ::google::protobuf::Message::GetClearImpl<MessageSet>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<MessageSet>(),
                ::google::protobuf::Message::GetSerializeImpl<MessageSet>(),
            PROTOBUF_FIELD_OFFSET(MessageSet, _impl_._cached_size_),
            false,
        },
        &MessageSet::kDescriptorMethods,
        &descriptor_table_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* MessageSet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 1, 0, 2> MessageSet::_table_ = {
  {
    0,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(MessageSet, _impl_._extensions_),
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MessageSet_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::google::protobuf::bridge::MessageSet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MessageSetWireFormatParseLoop, {0, 0}},
  }}, {{
    65535, 65535
  }}, {{
  }}, {{
    {},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MessageSet::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.bridge.MessageSet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MessageSet::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
   target =
      _impl_._extensions_.InternalSerializeMessageSetWithCachedSizesToArray(
          internal_default_instance(), target, stream);
  target = ::_pbi::InternalSerializeUnknownMessageSetItemsToArray(
      _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  return target;
}

PROTOBUF_NOINLINE ::size_t MessageSet::ByteSizeLong() const {
  // @@protoc_insertion_point(message_set_byte_size_start:google.protobuf.bridge.MessageSet)
  ::size_t total_size = _impl_._extensions_.MessageSetByteSize();
  if (_internal_metadata_.have_unknown_fields()) {
    total_size += ::_pbi::ComputeUnknownMessageSetItemsSize(_internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance));
  }
  _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void MessageSet::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MessageSet*>(&to_msg);
  auto& from = static_cast<const MessageSet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.bridge.MessageSet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageSet::CopyFrom(const MessageSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.bridge.MessageSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MessageSet::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const MessageSet&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(
          internal_default_instance())) {
    return false;
  }
  return true;
}

void MessageSet::InternalSwap(MessageSet* PROTOBUF_RESTRICT other) {
  using std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MessageSet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace bridge
}  // namespace protobuf
}  // namespace google
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_google_2fprotobuf_2fbridge_2fmessage_5fset_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
