// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: math/math.proto
// Protobuf C++ Version: 5.28.0-dev

#include "math/math.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace math {

inline constexpr vec2::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR vec2::vec2(::_pbi::ConstantInitialized)
    : ::google::protobuf::Message(_class_data_.base()),
      _impl_(::_pbi::ConstantInitialized()) {}
struct vec2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR vec2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~vec2DefaultTypeInternal() {}
  union {
    vec2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 vec2DefaultTypeInternal _vec2_default_instance_;
}  // namespace math
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_math_2fmath_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_math_2fmath_2eproto = nullptr;
const ::uint32_t
    TableStruct_math_2fmath_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::math::vec2, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::math::vec2, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::math::vec2, _impl_.y_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::math::vec2)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::math::_vec2_default_instance_._instance,
};
const char descriptor_table_protodef_math_2fmath_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017math/math.proto\022\004math\"\034\n\004vec2\022\t\n\001x\030\001 \001"
    "(\002\022\t\n\001y\030\002 \001(\002b\006proto3"
};
static ::absl::once_flag descriptor_table_math_2fmath_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_math_2fmath_2eproto = {
    false,
    false,
    61,
    descriptor_table_protodef_math_2fmath_2eproto,
    "math/math.proto",
    &descriptor_table_math_2fmath_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_math_2fmath_2eproto::offsets,
    file_level_enum_descriptors_math_2fmath_2eproto,
    file_level_service_descriptors_math_2fmath_2eproto,
};
namespace math {
// ===================================================================

class vec2::_Internal {
 public:
};

vec2::vec2(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:math.vec2)
}
vec2::vec2(
    ::google::protobuf::Arena* arena, const vec2& from)
    : vec2(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE vec2::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void vec2::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::y_));
}
vec2::~vec2() {
  // @@protoc_insertion_point(destructor:math.vec2)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void vec2::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    vec2::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &vec2::MergeImpl,
            ::google::protobuf::Message::GetDeleteImpl<vec2>(),
            ::google::protobuf::Message::GetNewImpl<vec2>(),
            ::google::protobuf::Message::GetClearImpl<vec2>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<vec2>(),
                ::google::protobuf::Message::GetSerializeImpl<vec2>(),
            PROTOBUF_FIELD_OFFSET(vec2, _impl_._cached_size_),
            false,
        },
        &vec2::kDescriptorMethods,
        &descriptor_table_math_2fmath_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* vec2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> vec2::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_vec2_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::math::vec2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(vec2, _impl_.y_)}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(vec2, _impl_.x_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(vec2, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(vec2, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void vec2::Clear() {
// @@protoc_insertion_point(message_clear_start:math.vec2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.y_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.y_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* vec2::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:math.vec2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // float x = 1;
  if (::absl::bit_cast<::uint32_t>(this->_internal_x()) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_x(), target);
  }

  // float y = 2;
  if (::absl::bit_cast<::uint32_t>(this->_internal_y()) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_y(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:math.vec2)
  return target;
}

::size_t vec2::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:math.vec2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(
      reinterpret_cast<const void*>(this));
   {
    // float x = 1;
    if (::absl::bit_cast<::uint32_t>(this->_internal_x()) != 0) {
      total_size += 5;
    }
    // float y = 2;
    if (::absl::bit_cast<::uint32_t>(this->_internal_y()) != 0) {
      total_size += 5;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void vec2::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<vec2*>(&to_msg);
  auto& from = static_cast<const vec2&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:math.vec2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void vec2::CopyFrom(const vec2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:math.vec2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void vec2::InternalSwap(vec2* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(vec2, _impl_.y_)
      + sizeof(vec2::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(vec2, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata vec2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace math
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_math_2fmath_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
