/*
* Created by boil on 2024/2/11.
*/

#ifndef RENDU_TASK_TASK_TASK_EXCEPTION_OPERATION_CANCELLED_EXCEPTION_H_
#define RENDU_TASK_TASK_TASK_EXCEPTION_OPERATION_CANCELLED_EXCEPTION_H_

#include "task_define.h"

TASK_NAMESPACE_BEGIN

class OperationCancelledException: public Exception{
};

TASK_NAMESPACE_END

#endif//RENDU_TASK_TASK_TASK_EXCEPTION_OPERATION_CANCELLED_EXCEPTION_H_
