// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/logger.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_core_2flogger_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_core_2flogger_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_core_2flogger_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2flogger_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_core_2flogger_2eproto;
namespace rendu {
namespace proto {
namespace core {
class LogSetting;
struct LogSettingDefaultTypeInternal;
extern LogSettingDefaultTypeInternal _LogSetting_default_instance_;
}  // namespace core
}  // namespace proto
}  // namespace rendu
PROTOBUF_NAMESPACE_OPEN
template<> ::rendu::proto::core::LogSetting* Arena::CreateMaybeMessage<::rendu::proto::core::LogSetting>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rendu {
namespace proto {
namespace core {

// ===================================================================

class LogSetting final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rendu.proto.core.LogSetting) */ {
 public:
  inline LogSetting() : LogSetting(nullptr) {}
  ~LogSetting() override;
  explicit PROTOBUF_CONSTEXPR LogSetting(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogSetting(const LogSetting& from);
  LogSetting(LogSetting&& from) noexcept
    : LogSetting() {
    *this = ::std::move(from);
  }

  inline LogSetting& operator=(const LogSetting& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogSetting& operator=(LogSetting&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogSetting& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogSetting* internal_default_instance() {
    return reinterpret_cast<const LogSetting*>(
               &_LogSetting_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogSetting& a, LogSetting& b) {
    a.Swap(&b);
  }
  inline void Swap(LogSetting* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogSetting* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogSetting* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogSetting>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogSetting& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogSetting& from) {
    LogSetting::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogSetting* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rendu.proto.core.LogSetting";
  }
  protected:
  explicit LogSetting(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 2,
    kPerHeaderFieldNumber = 3,
    kLevelFieldNumber = 1,
  };
  // string path = 2;
  void clear_path();
  const std::string& path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // string perHeader = 3;
  void clear_perheader();
  const std::string& perheader() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_perheader(ArgT0&& arg0, ArgT... args);
  std::string* mutable_perheader();
  PROTOBUF_NODISCARD std::string* release_perheader();
  void set_allocated_perheader(std::string* perheader);
  private:
  const std::string& _internal_perheader() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_perheader(const std::string& value);
  std::string* _internal_mutable_perheader();
  public:

  // int32 level = 1;
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rendu.proto.core.LogSetting)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr perheader_;
    int32_t level_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2flogger_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogSetting

// int32 level = 1;
inline void LogSetting::clear_level() {
  _impl_.level_ = 0;
}
inline int32_t LogSetting::_internal_level() const {
  return _impl_.level_;
}
inline int32_t LogSetting::level() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.LogSetting.level)
  return _internal_level();
}
inline void LogSetting::_internal_set_level(int32_t value) {
  
  _impl_.level_ = value;
}
inline void LogSetting::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:rendu.proto.core.LogSetting.level)
}

// string path = 2;
inline void LogSetting::clear_path() {
  _impl_.path_.ClearToEmpty();
}
inline const std::string& LogSetting::path() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.LogSetting.path)
  return _internal_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogSetting::set_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rendu.proto.core.LogSetting.path)
}
inline std::string* LogSetting::mutable_path() {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:rendu.proto.core.LogSetting.path)
  return _s;
}
inline const std::string& LogSetting::_internal_path() const {
  return _impl_.path_.Get();
}
inline void LogSetting::_internal_set_path(const std::string& value) {
  
  _impl_.path_.Set(value, GetArenaForAllocation());
}
inline std::string* LogSetting::_internal_mutable_path() {
  
  return _impl_.path_.Mutable(GetArenaForAllocation());
}
inline std::string* LogSetting::release_path() {
  // @@protoc_insertion_point(field_release:rendu.proto.core.LogSetting.path)
  return _impl_.path_.Release();
}
inline void LogSetting::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  _impl_.path_.SetAllocated(path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rendu.proto.core.LogSetting.path)
}

// string perHeader = 3;
inline void LogSetting::clear_perheader() {
  _impl_.perheader_.ClearToEmpty();
}
inline const std::string& LogSetting::perheader() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.LogSetting.perHeader)
  return _internal_perheader();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogSetting::set_perheader(ArgT0&& arg0, ArgT... args) {
 
 _impl_.perheader_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rendu.proto.core.LogSetting.perHeader)
}
inline std::string* LogSetting::mutable_perheader() {
  std::string* _s = _internal_mutable_perheader();
  // @@protoc_insertion_point(field_mutable:rendu.proto.core.LogSetting.perHeader)
  return _s;
}
inline const std::string& LogSetting::_internal_perheader() const {
  return _impl_.perheader_.Get();
}
inline void LogSetting::_internal_set_perheader(const std::string& value) {
  
  _impl_.perheader_.Set(value, GetArenaForAllocation());
}
inline std::string* LogSetting::_internal_mutable_perheader() {
  
  return _impl_.perheader_.Mutable(GetArenaForAllocation());
}
inline std::string* LogSetting::release_perheader() {
  // @@protoc_insertion_point(field_release:rendu.proto.core.LogSetting.perHeader)
  return _impl_.perheader_.Release();
}
inline void LogSetting::set_allocated_perheader(std::string* perheader) {
  if (perheader != nullptr) {
    
  } else {
    
  }
  _impl_.perheader_.SetAllocated(perheader, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.perheader_.IsDefault()) {
    _impl_.perheader_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rendu.proto.core.LogSetting.perHeader)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace proto
}  // namespace rendu

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_core_2flogger_2eproto
