// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/logger.proto

#include "core/logger.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rendu {
namespace proto {
namespace core {
PROTOBUF_CONSTEXPR LogSetting::LogSetting(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.perheader_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.level_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LogSettingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogSettingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogSettingDefaultTypeInternal() {}
  union {
    LogSetting _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogSettingDefaultTypeInternal _LogSetting_default_instance_;
}  // namespace core
}  // namespace proto
}  // namespace rendu
static ::_pb::Metadata file_level_metadata_core_2flogger_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_core_2flogger_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_core_2flogger_2eproto = nullptr;

const uint32_t TableStruct_core_2flogger_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _impl_.level_),
  PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _impl_.path_),
  PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _impl_.perheader_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rendu::proto::core::LogSetting)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rendu::proto::core::_LogSetting_default_instance_._instance,
};

const char descriptor_table_protodef_core_2flogger_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021core/logger.proto\022\020rendu.proto.core\"<\n"
  "\nLogSetting\022\r\n\005level\030\001 \001(\005\022\014\n\004path\030\002 \001(\t"
  "\022\021\n\tperHeader\030\003 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_core_2flogger_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_core_2flogger_2eproto = {
    false, false, 107, descriptor_table_protodef_core_2flogger_2eproto,
    "core/logger.proto",
    &descriptor_table_core_2flogger_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_core_2flogger_2eproto::offsets,
    file_level_metadata_core_2flogger_2eproto, file_level_enum_descriptors_core_2flogger_2eproto,
    file_level_service_descriptors_core_2flogger_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_core_2flogger_2eproto_getter() {
  return &descriptor_table_core_2flogger_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_core_2flogger_2eproto(&descriptor_table_core_2flogger_2eproto);
namespace rendu {
namespace proto {
namespace core {

// ===================================================================

class LogSetting::_Internal {
 public:
};

LogSetting::LogSetting(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rendu.proto.core.LogSetting)
}
LogSetting::LogSetting(const LogSetting& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LogSetting* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.path_){}
    , decltype(_impl_.perheader_){}
    , decltype(_impl_.level_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_path().empty()) {
    _this->_impl_.path_.Set(from._internal_path(), 
      _this->GetArenaForAllocation());
  }
  _impl_.perheader_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.perheader_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_perheader().empty()) {
    _this->_impl_.perheader_.Set(from._internal_perheader(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.level_ = from._impl_.level_;
  // @@protoc_insertion_point(copy_constructor:rendu.proto.core.LogSetting)
}

inline void LogSetting::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.path_){}
    , decltype(_impl_.perheader_){}
    , decltype(_impl_.level_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.perheader_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.perheader_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LogSetting::~LogSetting() {
  // @@protoc_insertion_point(destructor:rendu.proto.core.LogSetting)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LogSetting::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.path_.Destroy();
  _impl_.perheader_.Destroy();
}

void LogSetting::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LogSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:rendu.proto.core.LogSetting)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _impl_.perheader_.ClearToEmpty();
  _impl_.level_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogSetting::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 level = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string path = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rendu.proto.core.LogSetting.path"));
        } else
          goto handle_unusual;
        continue;
      // string perHeader = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_perheader();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "rendu.proto.core.LogSetting.perHeader"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LogSetting::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rendu.proto.core.LogSetting)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 level = 1;
  if (this->_internal_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_level(), target);
  }

  // string path = 2;
  if (!this->_internal_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rendu.proto.core.LogSetting.path");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_path(), target);
  }

  // string perHeader = 3;
  if (!this->_internal_perheader().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_perheader().data(), static_cast<int>(this->_internal_perheader().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "rendu.proto.core.LogSetting.perHeader");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_perheader(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rendu.proto.core.LogSetting)
  return target;
}

size_t LogSetting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rendu.proto.core.LogSetting)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 2;
  if (!this->_internal_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  // string perHeader = 3;
  if (!this->_internal_perheader().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_perheader());
  }

  // int32 level = 1;
  if (this->_internal_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_level());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LogSetting::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LogSetting::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LogSetting::GetClassData() const { return &_class_data_; }


void LogSetting::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LogSetting*>(&to_msg);
  auto& from = static_cast<const LogSetting&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rendu.proto.core.LogSetting)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  if (!from._internal_perheader().empty()) {
    _this->_internal_set_perheader(from._internal_perheader());
  }
  if (from._internal_level() != 0) {
    _this->_internal_set_level(from._internal_level());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LogSetting::CopyFrom(const LogSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rendu.proto.core.LogSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogSetting::IsInitialized() const {
  return true;
}

void LogSetting::InternalSwap(LogSetting* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.path_, lhs_arena,
      &other->_impl_.path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.perheader_, lhs_arena,
      &other->_impl_.perheader_, rhs_arena
  );
  swap(_impl_.level_, other->_impl_.level_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LogSetting::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2flogger_2eproto_getter, &descriptor_table_core_2flogger_2eproto_once,
      file_level_metadata_core_2flogger_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace proto
}  // namespace rendu
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rendu::proto::core::LogSetting*
Arena::CreateMaybeMessage< ::rendu::proto::core::LogSetting >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rendu::proto::core::LogSetting >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
