// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/logger.proto
// Protobuf C++ Version: 5.28.0-dev

#include "core/logger.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rendu {
namespace proto {
namespace core {

inline constexpr LogSetting::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        perheader_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        level_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LogSetting::LogSetting(::_pbi::ConstantInitialized)
    : ::google::protobuf::Message(_class_data_.base()),
      _impl_(::_pbi::ConstantInitialized()) {}
struct LogSettingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogSettingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogSettingDefaultTypeInternal() {}
  union {
    LogSetting _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogSettingDefaultTypeInternal _LogSetting_default_instance_;
}  // namespace core
}  // namespace proto
}  // namespace rendu
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_core_2flogger_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_core_2flogger_2eproto = nullptr;
const ::uint32_t
    TableStruct_core_2flogger_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _impl_.path_),
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::LogSetting, _impl_.perheader_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::rendu::proto::core::LogSetting)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::rendu::proto::core::_LogSetting_default_instance_._instance,
};
const char descriptor_table_protodef_core_2flogger_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021core/logger.proto\022\020rendu.proto.core\"<\n"
    "\nLogSetting\022\r\n\005level\030\001 \001(\005\022\014\n\004path\030\002 \001(\t"
    "\022\021\n\tperHeader\030\003 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_core_2flogger_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_core_2flogger_2eproto = {
    false,
    false,
    107,
    descriptor_table_protodef_core_2flogger_2eproto,
    "core/logger.proto",
    &descriptor_table_core_2flogger_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_core_2flogger_2eproto::offsets,
    file_level_enum_descriptors_core_2flogger_2eproto,
    file_level_service_descriptors_core_2flogger_2eproto,
};
namespace rendu {
namespace proto {
namespace core {
// ===================================================================

class LogSetting::_Internal {
 public:
};

LogSetting::LogSetting(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rendu.proto.core.LogSetting)
}
inline PROTOBUF_NDEBUG_INLINE LogSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rendu::proto::core::LogSetting& from_msg)
      : path_(arena, from.path_),
        perheader_(arena, from.perheader_),
        _cached_size_{0} {}

LogSetting::LogSetting(
    ::google::protobuf::Arena* arena,
    const LogSetting& from)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
  LogSetting* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.level_ = from._impl_.level_;

  // @@protoc_insertion_point(copy_constructor:rendu.proto.core.LogSetting)
}
inline PROTOBUF_NDEBUG_INLINE LogSetting::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : path_(arena),
        perheader_(arena),
        _cached_size_{0} {}

inline void LogSetting::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.level_ = {};
}
LogSetting::~LogSetting() {
  // @@protoc_insertion_point(destructor:rendu.proto.core.LogSetting)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LogSetting::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.path_.Destroy();
  _impl_.perheader_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    LogSetting::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &LogSetting::MergeImpl,
            ::google::protobuf::Message::GetDeleteImpl<LogSetting>(),
            ::google::protobuf::Message::GetNewImpl<LogSetting>(),
            ::google::protobuf::Message::GetClearImpl<LogSetting>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<LogSetting>(),
                ::google::protobuf::Message::GetSerializeImpl<LogSetting>(),
            PROTOBUF_FIELD_OFFSET(LogSetting, _impl_._cached_size_),
            false,
        },
        &LogSetting::kDescriptorMethods,
        &descriptor_table_core_2flogger_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* LogSetting::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 49, 2> LogSetting::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LogSetting_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rendu::proto::core::LogSetting>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 level = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LogSetting, _impl_.level_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LogSetting, _impl_.level_)}},
    // string path = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(LogSetting, _impl_.path_)}},
    // string perHeader = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(LogSetting, _impl_.perheader_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 level = 1;
    {PROTOBUF_FIELD_OFFSET(LogSetting, _impl_.level_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string path = 2;
    {PROTOBUF_FIELD_OFFSET(LogSetting, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string perHeader = 3;
    {PROTOBUF_FIELD_OFFSET(LogSetting, _impl_.perheader_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\0\4\11\0\0\0\0"
    "rendu.proto.core.LogSetting"
    "path"
    "perHeader"
  }},
};

PROTOBUF_NOINLINE void LogSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:rendu.proto.core.LogSetting)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _impl_.perheader_.ClearToEmpty();
  _impl_.level_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* LogSetting::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rendu.proto.core.LogSetting)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 level = 1;
  if (this->_internal_level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_level(), target);
  }

  // string path = 2;
  if (!this->_internal_path().empty()) {
    const std::string& _s = this->_internal_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rendu.proto.core.LogSetting.path");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string perHeader = 3;
  if (!this->_internal_perheader().empty()) {
    const std::string& _s = this->_internal_perheader();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rendu.proto.core.LogSetting.perHeader");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rendu.proto.core.LogSetting)
  return target;
}

::size_t LogSetting::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:rendu.proto.core.LogSetting)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(
      reinterpret_cast<const void*>(this));
   {
    // string path = 2;
    if (!this->_internal_path().empty()) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_path());
    }
    // string perHeader = 3;
    if (!this->_internal_perheader().empty()) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_perheader());
    }
    // int32 level = 1;
    if (this->_internal_level() != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_level());
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void LogSetting::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LogSetting*>(&to_msg);
  auto& from = static_cast<const LogSetting&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rendu.proto.core.LogSetting)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  if (!from._internal_perheader().empty()) {
    _this->_internal_set_perheader(from._internal_perheader());
  }
  if (from._internal_level() != 0) {
    _this->_impl_.level_ = from._impl_.level_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LogSetting::CopyFrom(const LogSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rendu.proto.core.LogSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LogSetting::InternalSwap(LogSetting* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.perheader_, &other->_impl_.perheader_, arena);
        swap(_impl_.level_, other->_impl_.level_);
}

::google::protobuf::Metadata LogSetting::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace proto
}  // namespace rendu
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_core_2flogger_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
