// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/logger.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_core_2flogger_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_core_2flogger_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_core_2flogger_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2flogger_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_core_2flogger_2eproto;
namespace rendu {
namespace proto {
namespace core {
class LogSetting;
struct LogSettingDefaultTypeInternal;
extern LogSettingDefaultTypeInternal _LogSetting_default_instance_;
}  // namespace core
}  // namespace proto
}  // namespace rendu
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace rendu {
namespace proto {
namespace core {

// ===================================================================


// -------------------------------------------------------------------

class LogSetting final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rendu.proto.core.LogSetting) */ {
 public:
  inline LogSetting() : LogSetting(nullptr) {}
  ~LogSetting() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LogSetting(
      ::google::protobuf::internal::ConstantInitialized);

  inline LogSetting(const LogSetting& from) : LogSetting(nullptr, from) {}
  inline LogSetting(LogSetting&& from) noexcept
      : LogSetting(nullptr, std::move(from)) {}
  inline LogSetting& operator=(const LogSetting& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogSetting& operator=(LogSetting&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogSetting& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogSetting* internal_default_instance() {
    return reinterpret_cast<const LogSetting*>(
        &_LogSetting_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LogSetting& a, LogSetting& b) { a.Swap(&b); }
  inline void Swap(LogSetting* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogSetting* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogSetting* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<LogSetting>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LogSetting& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LogSetting& from) { LogSetting::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(LogSetting* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "rendu.proto.core.LogSetting"; }

 protected:
  explicit LogSetting(::google::protobuf::Arena* arena);
  LogSetting(::google::protobuf::Arena* arena, const LogSetting& from);
  LogSetting(::google::protobuf::Arena* arena, LogSetting&& from) noexcept
      : LogSetting(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPathFieldNumber = 2,
    kPerHeaderFieldNumber = 3,
    kLevelFieldNumber = 1,
  };
  // string path = 2;
  void clear_path() ;
  const std::string& path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* value);

  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(
      const std::string& value);
  std::string* _internal_mutable_path();

  public:
  // string perHeader = 3;
  void clear_perheader() ;
  const std::string& perheader() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_perheader(Arg_&& arg, Args_... args);
  std::string* mutable_perheader();
  PROTOBUF_NODISCARD std::string* release_perheader();
  void set_allocated_perheader(std::string* value);

  private:
  const std::string& _internal_perheader() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_perheader(
      const std::string& value);
  std::string* _internal_mutable_perheader();

  public:
  // int32 level = 1;
  void clear_level() ;
  ::int32_t level() const;
  void set_level(::int32_t value);

  private:
  ::int32_t _internal_level() const;
  void _internal_set_level(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:rendu.proto.core.LogSetting)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      49, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_LogSetting_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LogSetting& from_msg);
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::google::protobuf::internal::ArenaStringPtr perheader_;
    ::int32_t level_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2flogger_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LogSetting

// int32 level = 1;
inline void LogSetting::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0;
}
inline ::int32_t LogSetting::level() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.LogSetting.level)
  return _internal_level();
}
inline void LogSetting::set_level(::int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:rendu.proto.core.LogSetting.level)
}
inline ::int32_t LogSetting::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.level_;
}
inline void LogSetting::_internal_set_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// string path = 2;
inline void LogSetting::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
}
inline const std::string& LogSetting::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rendu.proto.core.LogSetting.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LogSetting::set_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rendu.proto.core.LogSetting.path)
}
inline std::string* LogSetting::mutable_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:rendu.proto.core.LogSetting.path)
  return _s;
}
inline const std::string& LogSetting::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void LogSetting::_internal_set_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Set(value, GetArena());
}
inline std::string* LogSetting::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.path_.Mutable( GetArena());
}
inline std::string* LogSetting::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rendu.proto.core.LogSetting.path)
  return _impl_.path_.Release();
}
inline void LogSetting::set_allocated_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.path_.IsDefault()) {
          _impl_.path_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rendu.proto.core.LogSetting.path)
}

// string perHeader = 3;
inline void LogSetting::clear_perheader() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.perheader_.ClearToEmpty();
}
inline const std::string& LogSetting::perheader() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rendu.proto.core.LogSetting.perHeader)
  return _internal_perheader();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LogSetting::set_perheader(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.perheader_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rendu.proto.core.LogSetting.perHeader)
}
inline std::string* LogSetting::mutable_perheader() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_perheader();
  // @@protoc_insertion_point(field_mutable:rendu.proto.core.LogSetting.perHeader)
  return _s;
}
inline const std::string& LogSetting::_internal_perheader() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.perheader_.Get();
}
inline void LogSetting::_internal_set_perheader(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.perheader_.Set(value, GetArena());
}
inline std::string* LogSetting::_internal_mutable_perheader() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.perheader_.Mutable( GetArena());
}
inline std::string* LogSetting::release_perheader() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rendu.proto.core.LogSetting.perHeader)
  return _impl_.perheader_.Release();
}
inline void LogSetting::set_allocated_perheader(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.perheader_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.perheader_.IsDefault()) {
          _impl_.perheader_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rendu.proto.core.LogSetting.perHeader)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace proto
}  // namespace rendu


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_core_2flogger_2eproto_2epb_2eh
