// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/options.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_core_2foptions_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_core_2foptions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_core_2foptions_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2foptions_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_core_2foptions_2eproto;
namespace rendu {
namespace proto {
namespace core {
class Options;
struct OptionsDefaultTypeInternal;
extern OptionsDefaultTypeInternal _Options_default_instance_;
}  // namespace core
}  // namespace proto
}  // namespace rendu
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace rendu {
namespace proto {
namespace core {
enum DevelopModeType : int {
  Official = 0,
  Develop = 1,
  Pressure = 2,
  DevelopModeType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DevelopModeType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DevelopModeType_IsValid(int value);
extern const uint32_t DevelopModeType_internal_data_[];
constexpr DevelopModeType DevelopModeType_MIN = static_cast<DevelopModeType>(0);
constexpr DevelopModeType DevelopModeType_MAX = static_cast<DevelopModeType>(2);
constexpr int DevelopModeType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
DevelopModeType_descriptor();
template <typename T>
const std::string& DevelopModeType_Name(T value) {
  static_assert(std::is_same<T, DevelopModeType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DevelopModeType_Name().");
  return DevelopModeType_Name(static_cast<DevelopModeType>(value));
}
template <>
inline const std::string& DevelopModeType_Name(DevelopModeType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DevelopModeType_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool DevelopModeType_Parse(absl::string_view name, DevelopModeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DevelopModeType>(
      DevelopModeType_descriptor(), name, value);
}
enum AppType : int {
  Server = 0,
  Watcher = 1,
  GameTool = 2,
  ExcelExporter = 3,
  Proto2CS = 4,
  BenchmarkClient = 5,
  BenchmarkServer = 6,
  Demo = 10,
  LockStep = 11,
  AppType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AppType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AppType_IsValid(int value);
extern const uint32_t AppType_internal_data_[];
constexpr AppType AppType_MIN = static_cast<AppType>(0);
constexpr AppType AppType_MAX = static_cast<AppType>(11);
constexpr int AppType_ARRAYSIZE = 11 + 1;
const ::google::protobuf::EnumDescriptor*
AppType_descriptor();
template <typename T>
const std::string& AppType_Name(T value) {
  static_assert(std::is_same<T, AppType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AppType_Name().");
  return AppType_Name(static_cast<AppType>(value));
}
template <>
inline const std::string& AppType_Name(AppType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AppType_descriptor,
                                                 0, 11>(
      static_cast<int>(value));
}
inline bool AppType_Parse(absl::string_view name, AppType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AppType>(
      AppType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Options final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rendu.proto.core.Options) */ {
 public:
  inline Options() : Options(nullptr) {}
  ~Options() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Options(
      ::google::protobuf::internal::ConstantInitialized);

  inline Options(const Options& from) : Options(nullptr, from) {}
  inline Options(Options&& from) noexcept
      : Options(nullptr, std::move(from)) {}
  inline Options& operator=(const Options& from) {
    CopyFrom(from);
    return *this;
  }
  inline Options& operator=(Options&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Options& default_instance() {
    return *internal_default_instance();
  }
  static inline const Options* internal_default_instance() {
    return reinterpret_cast<const Options*>(
        &_Options_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Options& a, Options& b) { a.Swap(&b); }
  inline void Swap(Options* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Options* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Options* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Options>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Options& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Options& from) { Options::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Options* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "rendu.proto.core.Options"; }

 protected:
  explicit Options(::google::protobuf::Arena* arena);
  Options(::google::protobuf::Arena* arena, const Options& from);
  Options(::google::protobuf::Arena* arena, Options&& from) noexcept
      : Options(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStartConfigFieldNumber = 2,
    kAppTypeFieldNumber = 1,
    kProcessFieldNumber = 3,
    kDevelopFieldNumber = 4,
    kLogLevelFieldNumber = 5,
    kConsoleFieldNumber = 6,
  };
  // string startConfig = 2;
  void clear_startconfig() ;
  const std::string& startconfig() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_startconfig(Arg_&& arg, Args_... args);
  std::string* mutable_startconfig();
  PROTOBUF_NODISCARD std::string* release_startconfig();
  void set_allocated_startconfig(std::string* value);

  private:
  const std::string& _internal_startconfig() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_startconfig(
      const std::string& value);
  std::string* _internal_mutable_startconfig();

  public:
  // .rendu.proto.core.AppType appType = 1;
  void clear_apptype() ;
  ::rendu::proto::core::AppType apptype() const;
  void set_apptype(::rendu::proto::core::AppType value);

  private:
  ::rendu::proto::core::AppType _internal_apptype() const;
  void _internal_set_apptype(::rendu::proto::core::AppType value);

  public:
  // int32 process = 3;
  void clear_process() ;
  ::int32_t process() const;
  void set_process(::int32_t value);

  private:
  ::int32_t _internal_process() const;
  void _internal_set_process(::int32_t value);

  public:
  // .rendu.proto.core.DevelopModeType develop = 4;
  void clear_develop() ;
  ::rendu::proto::core::DevelopModeType develop() const;
  void set_develop(::rendu::proto::core::DevelopModeType value);

  private:
  ::rendu::proto::core::DevelopModeType _internal_develop() const;
  void _internal_set_develop(::rendu::proto::core::DevelopModeType value);

  public:
  // int32 logLevel = 5;
  void clear_loglevel() ;
  ::int32_t loglevel() const;
  void set_loglevel(::int32_t value);

  private:
  ::int32_t _internal_loglevel() const;
  void _internal_set_loglevel(::int32_t value);

  public:
  // int32 console = 6;
  void clear_console() ;
  ::int32_t console() const;
  void set_console(::int32_t value);

  private:
  ::int32_t _internal_console() const;
  void _internal_set_console(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:rendu.proto.core.Options)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      44, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Options_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Options& from_msg);
    ::google::protobuf::internal::ArenaStringPtr startconfig_;
    int apptype_;
    ::int32_t process_;
    int develop_;
    ::int32_t loglevel_;
    ::int32_t console_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2foptions_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Options

// .rendu.proto.core.AppType appType = 1;
inline void Options::clear_apptype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.apptype_ = 0;
}
inline ::rendu::proto::core::AppType Options::apptype() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.Options.appType)
  return _internal_apptype();
}
inline void Options::set_apptype(::rendu::proto::core::AppType value) {
  _internal_set_apptype(value);
  // @@protoc_insertion_point(field_set:rendu.proto.core.Options.appType)
}
inline ::rendu::proto::core::AppType Options::_internal_apptype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::rendu::proto::core::AppType>(_impl_.apptype_);
}
inline void Options::_internal_set_apptype(::rendu::proto::core::AppType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.apptype_ = value;
}

// string startConfig = 2;
inline void Options::clear_startconfig() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startconfig_.ClearToEmpty();
}
inline const std::string& Options::startconfig() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rendu.proto.core.Options.startConfig)
  return _internal_startconfig();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Options::set_startconfig(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startconfig_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rendu.proto.core.Options.startConfig)
}
inline std::string* Options::mutable_startconfig() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_startconfig();
  // @@protoc_insertion_point(field_mutable:rendu.proto.core.Options.startConfig)
  return _s;
}
inline const std::string& Options::_internal_startconfig() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.startconfig_.Get();
}
inline void Options::_internal_set_startconfig(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startconfig_.Set(value, GetArena());
}
inline std::string* Options::_internal_mutable_startconfig() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.startconfig_.Mutable( GetArena());
}
inline std::string* Options::release_startconfig() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rendu.proto.core.Options.startConfig)
  return _impl_.startconfig_.Release();
}
inline void Options::set_allocated_startconfig(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startconfig_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.startconfig_.IsDefault()) {
          _impl_.startconfig_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rendu.proto.core.Options.startConfig)
}

// int32 process = 3;
inline void Options::clear_process() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.process_ = 0;
}
inline ::int32_t Options::process() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.Options.process)
  return _internal_process();
}
inline void Options::set_process(::int32_t value) {
  _internal_set_process(value);
  // @@protoc_insertion_point(field_set:rendu.proto.core.Options.process)
}
inline ::int32_t Options::_internal_process() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.process_;
}
inline void Options::_internal_set_process(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.process_ = value;
}

// .rendu.proto.core.DevelopModeType develop = 4;
inline void Options::clear_develop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.develop_ = 0;
}
inline ::rendu::proto::core::DevelopModeType Options::develop() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.Options.develop)
  return _internal_develop();
}
inline void Options::set_develop(::rendu::proto::core::DevelopModeType value) {
  _internal_set_develop(value);
  // @@protoc_insertion_point(field_set:rendu.proto.core.Options.develop)
}
inline ::rendu::proto::core::DevelopModeType Options::_internal_develop() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::rendu::proto::core::DevelopModeType>(_impl_.develop_);
}
inline void Options::_internal_set_develop(::rendu::proto::core::DevelopModeType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.develop_ = value;
}

// int32 logLevel = 5;
inline void Options::clear_loglevel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.loglevel_ = 0;
}
inline ::int32_t Options::loglevel() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.Options.logLevel)
  return _internal_loglevel();
}
inline void Options::set_loglevel(::int32_t value) {
  _internal_set_loglevel(value);
  // @@protoc_insertion_point(field_set:rendu.proto.core.Options.logLevel)
}
inline ::int32_t Options::_internal_loglevel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.loglevel_;
}
inline void Options::_internal_set_loglevel(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.loglevel_ = value;
}

// int32 console = 6;
inline void Options::clear_console() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.console_ = 0;
}
inline ::int32_t Options::console() const {
  // @@protoc_insertion_point(field_get:rendu.proto.core.Options.console)
  return _internal_console();
}
inline void Options::set_console(::int32_t value) {
  _internal_set_console(value);
  // @@protoc_insertion_point(field_set:rendu.proto.core.Options.console)
}
inline ::int32_t Options::_internal_console() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.console_;
}
inline void Options::_internal_set_console(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.console_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace proto
}  // namespace rendu


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::rendu::proto::core::DevelopModeType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::rendu::proto::core::DevelopModeType>() {
  return ::rendu::proto::core::DevelopModeType_descriptor();
}
template <>
struct is_proto_enum<::rendu::proto::core::AppType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::rendu::proto::core::AppType>() {
  return ::rendu::proto::core::AppType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_core_2foptions_2eproto_2epb_2eh
