// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/options.proto
// Protobuf C++ Version: 5.28.0-dev

#include "core/options.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rendu {
namespace proto {
namespace core {

inline constexpr Options::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : startconfig_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        apptype_{static_cast< ::rendu::proto::core::AppType >(0)},
        process_{0},
        develop_{static_cast< ::rendu::proto::core::DevelopModeType >(0)},
        loglevel_{0},
        console_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Options::Options(::_pbi::ConstantInitialized)
    : ::google::protobuf::Message(_class_data_.base()),
      _impl_(::_pbi::ConstantInitialized()) {}
struct OptionsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OptionsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OptionsDefaultTypeInternal() {}
  union {
    Options _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OptionsDefaultTypeInternal _Options_default_instance_;
}  // namespace core
}  // namespace proto
}  // namespace rendu
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_core_2foptions_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_core_2foptions_2eproto = nullptr;
const ::uint32_t
    TableStruct_core_2foptions_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::Options, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::Options, _impl_.apptype_),
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::Options, _impl_.startconfig_),
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::Options, _impl_.process_),
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::Options, _impl_.develop_),
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::Options, _impl_.loglevel_),
        PROTOBUF_FIELD_OFFSET(::rendu::proto::core::Options, _impl_.console_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::rendu::proto::core::Options)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::rendu::proto::core::_Options_default_instance_._instance,
};
const char descriptor_table_protodef_core_2foptions_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022core/options.proto\022\020rendu.proto.core\"\262"
    "\001\n\007Options\022*\n\007appType\030\001 \001(\0162\031.rendu.prot"
    "o.core.AppType\022\023\n\013startConfig\030\002 \001(\t\022\017\n\007p"
    "rocess\030\003 \001(\005\0222\n\007develop\030\004 \001(\0162!.rendu.pr"
    "oto.core.DevelopModeType\022\020\n\010logLevel\030\005 \001"
    "(\005\022\017\n\007console\030\006 \001(\005*:\n\017DevelopModeType\022\014"
    "\n\010Official\020\000\022\013\n\007Develop\020\001\022\014\n\010Pressure\020\002*"
    "\223\001\n\007AppType\022\n\n\006Server\020\000\022\013\n\007Watcher\020\001\022\014\n\010"
    "GameTool\020\002\022\021\n\rExcelExporter\020\003\022\014\n\010Proto2C"
    "S\020\004\022\023\n\017BenchmarkClient\020\005\022\023\n\017BenchmarkSer"
    "ver\020\006\022\010\n\004Demo\020\n\022\014\n\010LockStep\020\013b\006proto3"
};
static ::absl::once_flag descriptor_table_core_2foptions_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_core_2foptions_2eproto = {
    false,
    false,
    437,
    descriptor_table_protodef_core_2foptions_2eproto,
    "core/options.proto",
    &descriptor_table_core_2foptions_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_core_2foptions_2eproto::offsets,
    file_level_enum_descriptors_core_2foptions_2eproto,
    file_level_service_descriptors_core_2foptions_2eproto,
};
namespace rendu {
namespace proto {
namespace core {
const ::google::protobuf::EnumDescriptor* DevelopModeType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_core_2foptions_2eproto);
  return file_level_enum_descriptors_core_2foptions_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DevelopModeType_internal_data_[] = {
    196608u, 0u, };
bool DevelopModeType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* AppType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_core_2foptions_2eproto);
  return file_level_enum_descriptors_core_2foptions_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t AppType_internal_data_[] = {
    458752u, 32u, 24u, };
bool AppType_IsValid(int value) {
  return 0 <= value && value <= 11 && ((3199u >> value) & 1) != 0;
}
// ===================================================================

class Options::_Internal {
 public:
};

Options::Options(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rendu.proto.core.Options)
}
inline PROTOBUF_NDEBUG_INLINE Options::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::rendu::proto::core::Options& from_msg)
      : startconfig_(arena, from.startconfig_),
        _cached_size_{0} {}

Options::Options(
    ::google::protobuf::Arena* arena,
    const Options& from)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
  Options* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, apptype_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, apptype_),
           offsetof(Impl_, console_) -
               offsetof(Impl_, apptype_) +
               sizeof(Impl_::console_));

  // @@protoc_insertion_point(copy_constructor:rendu.proto.core.Options)
}
inline PROTOBUF_NDEBUG_INLINE Options::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : startconfig_(arena),
        _cached_size_{0} {}

inline void Options::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, apptype_),
           0,
           offsetof(Impl_, console_) -
               offsetof(Impl_, apptype_) +
               sizeof(Impl_::console_));
}
Options::~Options() {
  // @@protoc_insertion_point(destructor:rendu.proto.core.Options)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Options::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.startconfig_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Options::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Options::MergeImpl,
            ::google::protobuf::Message::GetDeleteImpl<Options>(),
            ::google::protobuf::Message::GetNewImpl<Options>(),
            ::google::protobuf::Message::GetClearImpl<Options>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<Options>(),
                ::google::protobuf::Message::GetSerializeImpl<Options>(),
            PROTOBUF_FIELD_OFFSET(Options, _impl_._cached_size_),
            false,
        },
        &Options::kDescriptorMethods,
        &descriptor_table_core_2foptions_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Options::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 44, 2> Options::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Options_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rendu::proto::core::Options>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rendu.proto.core.AppType appType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Options, _impl_.apptype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Options, _impl_.apptype_)}},
    // string startConfig = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Options, _impl_.startconfig_)}},
    // int32 process = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Options, _impl_.process_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Options, _impl_.process_)}},
    // .rendu.proto.core.DevelopModeType develop = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Options, _impl_.develop_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Options, _impl_.develop_)}},
    // int32 logLevel = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Options, _impl_.loglevel_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Options, _impl_.loglevel_)}},
    // int32 console = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Options, _impl_.console_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(Options, _impl_.console_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .rendu.proto.core.AppType appType = 1;
    {PROTOBUF_FIELD_OFFSET(Options, _impl_.apptype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string startConfig = 2;
    {PROTOBUF_FIELD_OFFSET(Options, _impl_.startconfig_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 process = 3;
    {PROTOBUF_FIELD_OFFSET(Options, _impl_.process_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .rendu.proto.core.DevelopModeType develop = 4;
    {PROTOBUF_FIELD_OFFSET(Options, _impl_.develop_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 logLevel = 5;
    {PROTOBUF_FIELD_OFFSET(Options, _impl_.loglevel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 console = 6;
    {PROTOBUF_FIELD_OFFSET(Options, _impl_.console_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\30\0\13\0\0\0\0\0"
    "rendu.proto.core.Options"
    "startConfig"
  }},
};

PROTOBUF_NOINLINE void Options::Clear() {
// @@protoc_insertion_point(message_clear_start:rendu.proto.core.Options)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.startconfig_.ClearToEmpty();
  ::memset(&_impl_.apptype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.console_) -
      reinterpret_cast<char*>(&_impl_.apptype_)) + sizeof(_impl_.console_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Options::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rendu.proto.core.Options)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .rendu.proto.core.AppType appType = 1;
  if (this->_internal_apptype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_apptype(), target);
  }

  // string startConfig = 2;
  if (!this->_internal_startconfig().empty()) {
    const std::string& _s = this->_internal_startconfig();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rendu.proto.core.Options.startConfig");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int32 process = 3;
  if (this->_internal_process() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_process(), target);
  }

  // .rendu.proto.core.DevelopModeType develop = 4;
  if (this->_internal_develop() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        4, this->_internal_develop(), target);
  }

  // int32 logLevel = 5;
  if (this->_internal_loglevel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_loglevel(), target);
  }

  // int32 console = 6;
  if (this->_internal_console() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<6>(
            stream, this->_internal_console(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rendu.proto.core.Options)
  return target;
}

::size_t Options::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:rendu.proto.core.Options)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(
      reinterpret_cast<const void*>(this));
   {
    // string startConfig = 2;
    if (!this->_internal_startconfig().empty()) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_startconfig());
    }
    // .rendu.proto.core.AppType appType = 1;
    if (this->_internal_apptype() != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_apptype());
    }
    // int32 process = 3;
    if (this->_internal_process() != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_process());
    }
    // .rendu.proto.core.DevelopModeType develop = 4;
    if (this->_internal_develop() != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_develop());
    }
    // int32 logLevel = 5;
    if (this->_internal_loglevel() != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_loglevel());
    }
    // int32 console = 6;
    if (this->_internal_console() != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_console());
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void Options::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Options*>(&to_msg);
  auto& from = static_cast<const Options&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rendu.proto.core.Options)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_startconfig().empty()) {
    _this->_internal_set_startconfig(from._internal_startconfig());
  }
  if (from._internal_apptype() != 0) {
    _this->_impl_.apptype_ = from._impl_.apptype_;
  }
  if (from._internal_process() != 0) {
    _this->_impl_.process_ = from._impl_.process_;
  }
  if (from._internal_develop() != 0) {
    _this->_impl_.develop_ = from._impl_.develop_;
  }
  if (from._internal_loglevel() != 0) {
    _this->_impl_.loglevel_ = from._impl_.loglevel_;
  }
  if (from._internal_console() != 0) {
    _this->_impl_.console_ = from._impl_.console_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Options::CopyFrom(const Options& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rendu.proto.core.Options)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Options::InternalSwap(Options* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.startconfig_, &other->_impl_.startconfig_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Options, _impl_.console_)
      + sizeof(Options::_impl_.console_)
      - PROTOBUF_FIELD_OFFSET(Options, _impl_.apptype_)>(
          reinterpret_cast<char*>(&_impl_.apptype_),
          reinterpret_cast<char*>(&other->_impl_.apptype_));
}

::google::protobuf::Metadata Options::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace proto
}  // namespace rendu
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_core_2foptions_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
