// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: compiler/cpp/tools/analyze_profile_proto_test.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto;
namespace google {
namespace protobuf {
namespace compiler {
namespace tools {
class AnalyzeChild;
struct AnalyzeChildDefaultTypeInternal;
extern AnalyzeChildDefaultTypeInternal _AnalyzeChild_default_instance_;
class AnalyzeThis;
struct AnalyzeThisDefaultTypeInternal;
extern AnalyzeThisDefaultTypeInternal _AnalyzeThis_default_instance_;
class AnalyzeThis_Nested;
struct AnalyzeThis_NestedDefaultTypeInternal;
extern AnalyzeThis_NestedDefaultTypeInternal _AnalyzeThis_Nested_default_instance_;
}  // namespace tools
}  // namespace compiler
}  // namespace protobuf
}  // namespace google

namespace google {
namespace protobuf {
namespace compiler {
namespace tools {

// ===================================================================


// -------------------------------------------------------------------

class AnalyzeThis_Nested final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:google.protobuf.compiler.tools.AnalyzeThis.Nested) */ {
 public:
  inline AnalyzeThis_Nested() : AnalyzeThis_Nested(nullptr) {}
  ~AnalyzeThis_Nested() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnalyzeThis_Nested(
      ::google::protobuf::internal::ConstantInitialized);

  inline AnalyzeThis_Nested(const AnalyzeThis_Nested& from) : AnalyzeThis_Nested(nullptr, from) {}
  inline AnalyzeThis_Nested(AnalyzeThis_Nested&& from) noexcept
      : AnalyzeThis_Nested(nullptr, std::move(from)) {}
  inline AnalyzeThis_Nested& operator=(const AnalyzeThis_Nested& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnalyzeThis_Nested& operator=(AnalyzeThis_Nested&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnalyzeThis_Nested& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnalyzeThis_Nested* internal_default_instance() {
    return reinterpret_cast<const AnalyzeThis_Nested*>(
        &_AnalyzeThis_Nested_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AnalyzeThis_Nested& a, AnalyzeThis_Nested& b) { a.Swap(&b); }
  inline void Swap(AnalyzeThis_Nested* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnalyzeThis_Nested* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnalyzeThis_Nested* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<AnalyzeThis_Nested>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AnalyzeThis_Nested& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AnalyzeThis_Nested& from) { AnalyzeThis_Nested::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AnalyzeThis_Nested* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "google.protobuf.compiler.tools.AnalyzeThis.Nested"; }

 protected:
  explicit AnalyzeThis_Nested(::google::protobuf::Arena* arena);
  AnalyzeThis_Nested(::google::protobuf::Arena* arena, const AnalyzeThis_Nested& from);
  AnalyzeThis_Nested(::google::protobuf::Arena* arena, AnalyzeThis_Nested&& from) noexcept
      : AnalyzeThis_Nested(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOptionalStringFieldNumber = 2,
    kNextedIdFieldNumber = 1,
  };
  // optional string optional_string = 2;
  bool has_optional_string() const;
  void clear_optional_string() ;
  const std::string& optional_string() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_optional_string(Arg_&& arg, Args_... args);
  std::string* mutable_optional_string();
  PROTOBUF_NODISCARD std::string* release_optional_string();
  void set_allocated_optional_string(std::string* value);

  private:
  const std::string& _internal_optional_string() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_optional_string(
      const std::string& value);
  std::string* _internal_mutable_optional_string();

  public:
  // optional int32 nexted_id = 1;
  bool has_nexted_id() const;
  void clear_nexted_id() ;
  ::int32_t nexted_id() const;
  void set_nexted_id(::int32_t value);

  private:
  ::int32_t _internal_nexted_id() const;
  void _internal_set_nexted_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.tools.AnalyzeThis.Nested)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      73, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AnalyzeThis_Nested_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AnalyzeThis_Nested& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr optional_string_;
    ::int32_t nexted_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto;
};
// -------------------------------------------------------------------

class AnalyzeChild final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:google.protobuf.compiler.tools.AnalyzeChild) */ {
 public:
  inline AnalyzeChild() : AnalyzeChild(nullptr) {}
  ~AnalyzeChild() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnalyzeChild(
      ::google::protobuf::internal::ConstantInitialized);

  inline AnalyzeChild(const AnalyzeChild& from) : AnalyzeChild(nullptr, from) {}
  inline AnalyzeChild(AnalyzeChild&& from) noexcept
      : AnalyzeChild(nullptr, std::move(from)) {}
  inline AnalyzeChild& operator=(const AnalyzeChild& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnalyzeChild& operator=(AnalyzeChild&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnalyzeChild& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnalyzeChild* internal_default_instance() {
    return reinterpret_cast<const AnalyzeChild*>(
        &_AnalyzeChild_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AnalyzeChild& a, AnalyzeChild& b) { a.Swap(&b); }
  inline void Swap(AnalyzeChild* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnalyzeChild* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnalyzeChild* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<AnalyzeChild>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AnalyzeChild& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AnalyzeChild& from) { AnalyzeChild::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AnalyzeChild* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "google.protobuf.compiler.tools.AnalyzeChild"; }

 protected:
  explicit AnalyzeChild(::google::protobuf::Arena* arena);
  AnalyzeChild(::google::protobuf::Arena* arena, const AnalyzeChild& from);
  AnalyzeChild(::google::protobuf::Arena* arena, AnalyzeChild&& from) noexcept
      : AnalyzeChild(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChildFieldNumber = 2,
    kChildIdFieldNumber = 1,
  };
  // optional .google.protobuf.compiler.tools.AnalyzeChild child = 2;
  bool has_child() const;
  void clear_child() ;
  const ::google::protobuf::compiler::tools::AnalyzeChild& child() const;
  PROTOBUF_NODISCARD ::google::protobuf::compiler::tools::AnalyzeChild* release_child();
  ::google::protobuf::compiler::tools::AnalyzeChild* mutable_child();
  void set_allocated_child(::google::protobuf::compiler::tools::AnalyzeChild* value);
  void unsafe_arena_set_allocated_child(::google::protobuf::compiler::tools::AnalyzeChild* value);
  ::google::protobuf::compiler::tools::AnalyzeChild* unsafe_arena_release_child();

  private:
  const ::google::protobuf::compiler::tools::AnalyzeChild& _internal_child() const;
  ::google::protobuf::compiler::tools::AnalyzeChild* _internal_mutable_child();

  public:
  // optional int32 child_id = 1;
  bool has_child_id() const;
  void clear_child_id() ;
  ::int32_t child_id() const;
  void set_child_id(::int32_t value);

  private:
  ::int32_t _internal_child_id() const;
  void _internal_set_child_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.tools.AnalyzeChild)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AnalyzeChild_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AnalyzeChild& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::compiler::tools::AnalyzeChild* child_;
    ::int32_t child_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto;
};
// -------------------------------------------------------------------

class AnalyzeThis final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:google.protobuf.compiler.tools.AnalyzeThis) */ {
 public:
  inline AnalyzeThis() : AnalyzeThis(nullptr) {}
  ~AnalyzeThis() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnalyzeThis(
      ::google::protobuf::internal::ConstantInitialized);

  inline AnalyzeThis(const AnalyzeThis& from) : AnalyzeThis(nullptr, from) {}
  inline AnalyzeThis(AnalyzeThis&& from) noexcept
      : AnalyzeThis(nullptr, std::move(from)) {}
  inline AnalyzeThis& operator=(const AnalyzeThis& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnalyzeThis& operator=(AnalyzeThis&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnalyzeThis& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnalyzeThis* internal_default_instance() {
    return reinterpret_cast<const AnalyzeThis*>(
        &_AnalyzeThis_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(AnalyzeThis& a, AnalyzeThis& b) { a.Swap(&b); }
  inline void Swap(AnalyzeThis* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnalyzeThis* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnalyzeThis* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<AnalyzeThis>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AnalyzeThis& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AnalyzeThis& from) { AnalyzeThis::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AnalyzeThis* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "google.protobuf.compiler.tools.AnalyzeThis"; }

 protected:
  explicit AnalyzeThis(::google::protobuf::Arena* arena);
  AnalyzeThis(::google::protobuf::Arena* arena, const AnalyzeThis& from);
  AnalyzeThis(::google::protobuf::Arena* arena, AnalyzeThis&& from) noexcept
      : AnalyzeThis(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Nested = AnalyzeThis_Nested;

  // accessors -------------------------------------------------------
  enum : int {
    kRepeatedStringFieldNumber = 3,
    kRepeatedChildFieldNumber = 5,
    kOptionalStringFieldNumber = 2,
    kOptionalChildFieldNumber = 4,
    kNestedFieldNumber = 6,
    kIdFieldNumber = 1,
  };
  // repeated string repeated_string = 3;
  int repeated_string_size() const;
  private:
  int _internal_repeated_string_size() const;

  public:
  void clear_repeated_string() ;
  const std::string& repeated_string(int index) const;
  std::string* mutable_repeated_string(int index);
  void set_repeated_string(int index, const std::string& value);
  void set_repeated_string(int index, std::string&& value);
  void set_repeated_string(int index, const char* value);
  void set_repeated_string(int index, const char* value, std::size_t size);
  void set_repeated_string(int index, absl::string_view value);
  std::string* add_repeated_string();
  void add_repeated_string(const std::string& value);
  void add_repeated_string(std::string&& value);
  void add_repeated_string(const char* value);
  void add_repeated_string(const char* value, std::size_t size);
  void add_repeated_string(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& repeated_string() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_repeated_string();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_repeated_string() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_repeated_string();

  public:
  // repeated .google.protobuf.compiler.tools.AnalyzeChild repeated_child = 5;
  int repeated_child_size() const;
  private:
  int _internal_repeated_child_size() const;

  public:
  void clear_repeated_child() ;
  ::google::protobuf::compiler::tools::AnalyzeChild* mutable_repeated_child(int index);
  ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>* mutable_repeated_child();

  private:
  const ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>& _internal_repeated_child() const;
  ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>* _internal_mutable_repeated_child();
  public:
  const ::google::protobuf::compiler::tools::AnalyzeChild& repeated_child(int index) const;
  ::google::protobuf::compiler::tools::AnalyzeChild* add_repeated_child();
  const ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>& repeated_child() const;
  // optional string optional_string = 2;
  bool has_optional_string() const;
  void clear_optional_string() ;
  const std::string& optional_string() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_optional_string(Arg_&& arg, Args_... args);
  std::string* mutable_optional_string();
  PROTOBUF_NODISCARD std::string* release_optional_string();
  void set_allocated_optional_string(std::string* value);

  private:
  const std::string& _internal_optional_string() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_optional_string(
      const std::string& value);
  std::string* _internal_mutable_optional_string();

  public:
  // optional .google.protobuf.compiler.tools.AnalyzeChild optional_child = 4;
  bool has_optional_child() const;
  void clear_optional_child() ;
  const ::google::protobuf::compiler::tools::AnalyzeChild& optional_child() const;
  PROTOBUF_NODISCARD ::google::protobuf::compiler::tools::AnalyzeChild* release_optional_child();
  ::google::protobuf::compiler::tools::AnalyzeChild* mutable_optional_child();
  void set_allocated_optional_child(::google::protobuf::compiler::tools::AnalyzeChild* value);
  void unsafe_arena_set_allocated_optional_child(::google::protobuf::compiler::tools::AnalyzeChild* value);
  ::google::protobuf::compiler::tools::AnalyzeChild* unsafe_arena_release_optional_child();

  private:
  const ::google::protobuf::compiler::tools::AnalyzeChild& _internal_optional_child() const;
  ::google::protobuf::compiler::tools::AnalyzeChild* _internal_mutable_optional_child();

  public:
  // optional .google.protobuf.compiler.tools.AnalyzeThis.Nested nested = 6;
  bool has_nested() const;
  void clear_nested() ;
  const ::google::protobuf::compiler::tools::AnalyzeThis_Nested& nested() const;
  PROTOBUF_NODISCARD ::google::protobuf::compiler::tools::AnalyzeThis_Nested* release_nested();
  ::google::protobuf::compiler::tools::AnalyzeThis_Nested* mutable_nested();
  void set_allocated_nested(::google::protobuf::compiler::tools::AnalyzeThis_Nested* value);
  void unsafe_arena_set_allocated_nested(::google::protobuf::compiler::tools::AnalyzeThis_Nested* value);
  ::google::protobuf::compiler::tools::AnalyzeThis_Nested* unsafe_arena_release_nested();

  private:
  const ::google::protobuf::compiler::tools::AnalyzeThis_Nested& _internal_nested() const;
  ::google::protobuf::compiler::tools::AnalyzeThis_Nested* _internal_mutable_nested();

  public:
  // optional int32 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.tools.AnalyzeThis)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 3,
      81, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AnalyzeThis_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AnalyzeThis& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<std::string> repeated_string_;
    ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::tools::AnalyzeChild > repeated_child_;
    ::google::protobuf::internal::ArenaStringPtr optional_string_;
    ::google::protobuf::compiler::tools::AnalyzeChild* optional_child_;
    ::google::protobuf::compiler::tools::AnalyzeThis_Nested* nested_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AnalyzeChild

// optional int32 child_id = 1;
inline bool AnalyzeChild::has_child_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AnalyzeChild::clear_child_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.child_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t AnalyzeChild::child_id() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeChild.child_id)
  return _internal_child_id();
}
inline void AnalyzeChild::set_child_id(::int32_t value) {
  _internal_set_child_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.tools.AnalyzeChild.child_id)
}
inline ::int32_t AnalyzeChild::_internal_child_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.child_id_;
}
inline void AnalyzeChild::_internal_set_child_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.child_id_ = value;
}

// optional .google.protobuf.compiler.tools.AnalyzeChild child = 2;
inline bool AnalyzeChild::has_child() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.child_ != nullptr);
  return value;
}
inline void AnalyzeChild::clear_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.child_ != nullptr) _impl_.child_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::google::protobuf::compiler::tools::AnalyzeChild& AnalyzeChild::_internal_child() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::compiler::tools::AnalyzeChild* p = _impl_.child_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::compiler::tools::AnalyzeChild&>(::google::protobuf::compiler::tools::_AnalyzeChild_default_instance_);
}
inline const ::google::protobuf::compiler::tools::AnalyzeChild& AnalyzeChild::child() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeChild.child)
  return _internal_child();
}
inline void AnalyzeChild::unsafe_arena_set_allocated_child(::google::protobuf::compiler::tools::AnalyzeChild* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.child_);
  }
  _impl_.child_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeChild*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.protobuf.compiler.tools.AnalyzeChild.child)
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeChild::release_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::compiler::tools::AnalyzeChild* released = _impl_.child_;
  _impl_.child_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeChild::unsafe_arena_release_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:google.protobuf.compiler.tools.AnalyzeChild.child)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::compiler::tools::AnalyzeChild* temp = _impl_.child_;
  _impl_.child_ = nullptr;
  return temp;
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeChild::_internal_mutable_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.child_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::compiler::tools::AnalyzeChild>(GetArena());
    _impl_.child_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeChild*>(p);
  }
  return _impl_.child_;
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeChild::mutable_child() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::compiler::tools::AnalyzeChild* _msg = _internal_mutable_child();
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.tools.AnalyzeChild.child)
  return _msg;
}
inline void AnalyzeChild::set_allocated_child(::google::protobuf::compiler::tools::AnalyzeChild* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.child_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.child_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeChild*>(value);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.compiler.tools.AnalyzeChild.child)
}

// -------------------------------------------------------------------

// AnalyzeThis_Nested

// optional int32 nexted_id = 1;
inline bool AnalyzeThis_Nested::has_nexted_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AnalyzeThis_Nested::clear_nexted_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nexted_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t AnalyzeThis_Nested::nexted_id() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.Nested.nexted_id)
  return _internal_nexted_id();
}
inline void AnalyzeThis_Nested::set_nexted_id(::int32_t value) {
  _internal_set_nexted_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.tools.AnalyzeThis.Nested.nexted_id)
}
inline ::int32_t AnalyzeThis_Nested::_internal_nexted_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nexted_id_;
}
inline void AnalyzeThis_Nested::_internal_set_nexted_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nexted_id_ = value;
}

// optional string optional_string = 2;
inline bool AnalyzeThis_Nested::has_optional_string() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void AnalyzeThis_Nested::clear_optional_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optional_string_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AnalyzeThis_Nested::optional_string() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.Nested.optional_string)
  return _internal_optional_string();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AnalyzeThis_Nested::set_optional_string(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.optional_string_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.tools.AnalyzeThis.Nested.optional_string)
}
inline std::string* AnalyzeThis_Nested::mutable_optional_string() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_optional_string();
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.tools.AnalyzeThis.Nested.optional_string)
  return _s;
}
inline const std::string& AnalyzeThis_Nested::_internal_optional_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optional_string_.Get();
}
inline void AnalyzeThis_Nested::_internal_set_optional_string(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.optional_string_.Set(value, GetArena());
}
inline std::string* AnalyzeThis_Nested::_internal_mutable_optional_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.optional_string_.Mutable( GetArena());
}
inline std::string* AnalyzeThis_Nested::release_optional_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:google.protobuf.compiler.tools.AnalyzeThis.Nested.optional_string)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.optional_string_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.optional_string_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void AnalyzeThis_Nested::set_allocated_optional_string(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.optional_string_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.optional_string_.IsDefault()) {
          _impl_.optional_string_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.compiler.tools.AnalyzeThis.Nested.optional_string)
}

// -------------------------------------------------------------------

// AnalyzeThis

// optional int32 id = 1;
inline bool AnalyzeThis::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void AnalyzeThis::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t AnalyzeThis::id() const {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.id)
  return _internal_id();
}
inline void AnalyzeThis::set_id(::int32_t value) {
  _internal_set_id(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.tools.AnalyzeThis.id)
}
inline ::int32_t AnalyzeThis::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void AnalyzeThis::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// optional string optional_string = 2;
inline bool AnalyzeThis::has_optional_string() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void AnalyzeThis::clear_optional_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optional_string_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AnalyzeThis::optional_string() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.optional_string)
  return _internal_optional_string();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AnalyzeThis::set_optional_string(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.optional_string_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.tools.AnalyzeThis.optional_string)
}
inline std::string* AnalyzeThis::mutable_optional_string() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_optional_string();
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.tools.AnalyzeThis.optional_string)
  return _s;
}
inline const std::string& AnalyzeThis::_internal_optional_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optional_string_.Get();
}
inline void AnalyzeThis::_internal_set_optional_string(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.optional_string_.Set(value, GetArena());
}
inline std::string* AnalyzeThis::_internal_mutable_optional_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.optional_string_.Mutable( GetArena());
}
inline std::string* AnalyzeThis::release_optional_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:google.protobuf.compiler.tools.AnalyzeThis.optional_string)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.optional_string_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.optional_string_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void AnalyzeThis::set_allocated_optional_string(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.optional_string_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.optional_string_.IsDefault()) {
          _impl_.optional_string_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.compiler.tools.AnalyzeThis.optional_string)
}

// repeated string repeated_string = 3;
inline int AnalyzeThis::_internal_repeated_string_size() const {
  return _internal_repeated_string().size();
}
inline int AnalyzeThis::repeated_string_size() const {
  return _internal_repeated_string_size();
}
inline void AnalyzeThis::clear_repeated_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.repeated_string_.Clear();
}
inline std::string* AnalyzeThis::add_repeated_string()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_repeated_string()->Add();
  // @@protoc_insertion_point(field_add_mutable:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
  return _s;
}
inline const std::string& AnalyzeThis::repeated_string(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
  return _internal_repeated_string().Get(index);
}
inline std::string* AnalyzeThis::mutable_repeated_string(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
  return _internal_mutable_repeated_string()->Mutable(index);
}
inline void AnalyzeThis::set_repeated_string(int index, const std::string& value) {
  _internal_mutable_repeated_string()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::set_repeated_string(int index, std::string&& value) {
  _internal_mutable_repeated_string()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::set_repeated_string(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_repeated_string()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::set_repeated_string(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_repeated_string()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::set_repeated_string(int index, absl::string_view value) {
  _internal_mutable_repeated_string()->Mutable(index)->assign(
      value.data(), value.size());
  // @@protoc_insertion_point(field_set_string_piece:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::add_repeated_string(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_repeated_string()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::add_repeated_string(std::string&& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_repeated_string()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::add_repeated_string(const char* value) {
  ABSL_DCHECK(value != nullptr);
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_repeated_string()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::add_repeated_string(const char* value, std::size_t size) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_repeated_string()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline void AnalyzeThis::add_repeated_string(absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_repeated_string()->Add()->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_add_string_piece:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
AnalyzeThis::repeated_string() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
  return _internal_repeated_string();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
AnalyzeThis::mutable_repeated_string() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:google.protobuf.compiler.tools.AnalyzeThis.repeated_string)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_repeated_string();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
AnalyzeThis::_internal_repeated_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.repeated_string_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
AnalyzeThis::_internal_mutable_repeated_string() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.repeated_string_;
}

// optional .google.protobuf.compiler.tools.AnalyzeChild optional_child = 4;
inline bool AnalyzeThis::has_optional_child() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.optional_child_ != nullptr);
  return value;
}
inline void AnalyzeThis::clear_optional_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.optional_child_ != nullptr) _impl_.optional_child_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::google::protobuf::compiler::tools::AnalyzeChild& AnalyzeThis::_internal_optional_child() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::compiler::tools::AnalyzeChild* p = _impl_.optional_child_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::compiler::tools::AnalyzeChild&>(::google::protobuf::compiler::tools::_AnalyzeChild_default_instance_);
}
inline const ::google::protobuf::compiler::tools::AnalyzeChild& AnalyzeThis::optional_child() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.optional_child)
  return _internal_optional_child();
}
inline void AnalyzeThis::unsafe_arena_set_allocated_optional_child(::google::protobuf::compiler::tools::AnalyzeChild* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.optional_child_);
  }
  _impl_.optional_child_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeChild*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.protobuf.compiler.tools.AnalyzeThis.optional_child)
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeThis::release_optional_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::compiler::tools::AnalyzeChild* released = _impl_.optional_child_;
  _impl_.optional_child_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeThis::unsafe_arena_release_optional_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:google.protobuf.compiler.tools.AnalyzeThis.optional_child)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::compiler::tools::AnalyzeChild* temp = _impl_.optional_child_;
  _impl_.optional_child_ = nullptr;
  return temp;
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeThis::_internal_mutable_optional_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.optional_child_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::compiler::tools::AnalyzeChild>(GetArena());
    _impl_.optional_child_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeChild*>(p);
  }
  return _impl_.optional_child_;
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeThis::mutable_optional_child() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::google::protobuf::compiler::tools::AnalyzeChild* _msg = _internal_mutable_optional_child();
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.tools.AnalyzeThis.optional_child)
  return _msg;
}
inline void AnalyzeThis::set_allocated_optional_child(::google::protobuf::compiler::tools::AnalyzeChild* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.optional_child_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.optional_child_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeChild*>(value);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.compiler.tools.AnalyzeThis.optional_child)
}

// repeated .google.protobuf.compiler.tools.AnalyzeChild repeated_child = 5;
inline int AnalyzeThis::_internal_repeated_child_size() const {
  return _internal_repeated_child().size();
}
inline int AnalyzeThis::repeated_child_size() const {
  return _internal_repeated_child_size();
}
inline void AnalyzeThis::clear_repeated_child() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.repeated_child_.Clear();
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeThis::mutable_repeated_child(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.tools.AnalyzeThis.repeated_child)
  return _internal_mutable_repeated_child()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>* AnalyzeThis::mutable_repeated_child()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:google.protobuf.compiler.tools.AnalyzeThis.repeated_child)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_repeated_child();
}
inline const ::google::protobuf::compiler::tools::AnalyzeChild& AnalyzeThis::repeated_child(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.repeated_child)
  return _internal_repeated_child().Get(index);
}
inline ::google::protobuf::compiler::tools::AnalyzeChild* AnalyzeThis::add_repeated_child() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::compiler::tools::AnalyzeChild* _add = _internal_mutable_repeated_child()->Add();
  // @@protoc_insertion_point(field_add:google.protobuf.compiler.tools.AnalyzeThis.repeated_child)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>& AnalyzeThis::repeated_child() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:google.protobuf.compiler.tools.AnalyzeThis.repeated_child)
  return _internal_repeated_child();
}
inline const ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>&
AnalyzeThis::_internal_repeated_child() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.repeated_child_;
}
inline ::google::protobuf::RepeatedPtrField<::google::protobuf::compiler::tools::AnalyzeChild>*
AnalyzeThis::_internal_mutable_repeated_child() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.repeated_child_;
}

// optional .google.protobuf.compiler.tools.AnalyzeThis.Nested nested = 6;
inline bool AnalyzeThis::has_nested() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.nested_ != nullptr);
  return value;
}
inline void AnalyzeThis::clear_nested() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.nested_ != nullptr) _impl_.nested_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::google::protobuf::compiler::tools::AnalyzeThis_Nested& AnalyzeThis::_internal_nested() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::compiler::tools::AnalyzeThis_Nested* p = _impl_.nested_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::compiler::tools::AnalyzeThis_Nested&>(::google::protobuf::compiler::tools::_AnalyzeThis_Nested_default_instance_);
}
inline const ::google::protobuf::compiler::tools::AnalyzeThis_Nested& AnalyzeThis::nested() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:google.protobuf.compiler.tools.AnalyzeThis.nested)
  return _internal_nested();
}
inline void AnalyzeThis::unsafe_arena_set_allocated_nested(::google::protobuf::compiler::tools::AnalyzeThis_Nested* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.nested_);
  }
  _impl_.nested_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeThis_Nested*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.protobuf.compiler.tools.AnalyzeThis.nested)
}
inline ::google::protobuf::compiler::tools::AnalyzeThis_Nested* AnalyzeThis::release_nested() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::google::protobuf::compiler::tools::AnalyzeThis_Nested* released = _impl_.nested_;
  _impl_.nested_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::compiler::tools::AnalyzeThis_Nested* AnalyzeThis::unsafe_arena_release_nested() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:google.protobuf.compiler.tools.AnalyzeThis.nested)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::google::protobuf::compiler::tools::AnalyzeThis_Nested* temp = _impl_.nested_;
  _impl_.nested_ = nullptr;
  return temp;
}
inline ::google::protobuf::compiler::tools::AnalyzeThis_Nested* AnalyzeThis::_internal_mutable_nested() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.nested_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::compiler::tools::AnalyzeThis_Nested>(GetArena());
    _impl_.nested_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeThis_Nested*>(p);
  }
  return _impl_.nested_;
}
inline ::google::protobuf::compiler::tools::AnalyzeThis_Nested* AnalyzeThis::mutable_nested() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::google::protobuf::compiler::tools::AnalyzeThis_Nested* _msg = _internal_mutable_nested();
  // @@protoc_insertion_point(field_mutable:google.protobuf.compiler.tools.AnalyzeThis.nested)
  return _msg;
}
inline void AnalyzeThis::set_allocated_nested(::google::protobuf::compiler::tools::AnalyzeThis_Nested* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.nested_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.nested_ = reinterpret_cast<::google::protobuf::compiler::tools::AnalyzeThis_Nested*>(value);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.compiler.tools.AnalyzeThis.nested)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace tools
}  // namespace compiler
}  // namespace protobuf
}  // namespace google


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_compiler_2fcpp_2ftools_2fanalyze_5fprofile_5fproto_5ftest_2eproto_2epb_2eh
