set(core_dir ${CMAKE_CURRENT_SOURCE_DIR}/core)

CollectHeaderFiles(
    ${core_dir}/core
    caf_core_headers
)

set(caf_core_files
    ${core_dir}/src/abstract_actor.cpp
    ${core_dir}/src/abstract_channel.cpp
    ${core_dir}/src/abstract_group.cpp
    ${core_dir}/src/action.cpp
    ${core_dir}/src/actor.cpp
    ${core_dir}/src/actor_addr.cpp
    ${core_dir}/src/actor_clock.cpp
    ${core_dir}/src/actor_companion.cpp
    ${core_dir}/src/actor_config.cpp
    ${core_dir}/src/actor_control_block.cpp
    ${core_dir}/src/actor_ostream.cpp
    ${core_dir}/src/actor_pool.cpp
    ${core_dir}/src/actor_profiler.cpp
    ${core_dir}/src/actor_proxy.cpp
    ${core_dir}/src/actor_registry.cpp
    ${core_dir}/src/actor_system.cpp
    ${core_dir}/src/actor_system_config.cpp
    ${core_dir}/src/async/batch.cpp
    ${core_dir}/src/async/consumer.cpp
    ${core_dir}/src/async/execution_context.cpp
    ${core_dir}/src/async/producer.cpp
    ${core_dir}/src/attachable.cpp
    ${core_dir}/src/behavior.cpp
    ${core_dir}/src/binary_deserializer.cpp
    ${core_dir}/src/binary_serializer.cpp
    ${core_dir}/src/blocking_actor.cpp
    ${core_dir}/src/config_option.cpp
    ${core_dir}/src/config_option_adder.cpp
    ${core_dir}/src/config_option_set.cpp
    ${core_dir}/src/config_value.cpp
    ${core_dir}/src/config_value_reader.cpp
    ${core_dir}/src/config_value_writer.cpp
    ${core_dir}/src/decorator/sequencer.cpp
    ${core_dir}/src/default_attachable.cpp
    ${core_dir}/src/deserializer.cpp
    ${core_dir}/src/detail/abstract_worker.cpp
    ${core_dir}/src/detail/abstract_worker_hub.cpp
    ${core_dir}/src/detail/atomic_ref_counted.cpp
    ${core_dir}/src/detail/base64.cpp
    ${core_dir}/src/detail/behavior_impl.cpp
    ${core_dir}/src/detail/behavior_stack.cpp
    ${core_dir}/src/detail/blocking_behavior.cpp
    ${core_dir}/src/detail/config_consumer.cpp
    ${core_dir}/src/detail/get_mac_addresses.cpp
    ${core_dir}/src/detail/get_process_id.cpp
    ${core_dir}/src/detail/get_root_uuid.cpp
    ${core_dir}/src/detail/glob_match.cpp
    ${core_dir}/src/detail/group_tunnel.cpp
    ${core_dir}/src/detail/invoke_result_visitor.cpp
    ${core_dir}/src/detail/json.cpp
    ${core_dir}/src/detail/latch.cpp
    ${core_dir}/src/detail/local_group_module.cpp
    ${core_dir}/src/detail/message_builder_element.cpp
    ${core_dir}/src/detail/message_data.cpp
    ${core_dir}/src/detail/meta_object.cpp
    ${core_dir}/src/detail/monotonic_buffer_resource.cpp
    ${core_dir}/src/detail/parse.cpp
    ${core_dir}/src/detail/parser/chars.cpp
    ${core_dir}/src/detail/plain_ref_counted.cpp
    ${core_dir}/src/detail/pretty_type_name.cpp
    ${core_dir}/src/detail/print.cpp
    ${core_dir}/src/detail/private_thread.cpp
    ${core_dir}/src/detail/private_thread_pool.cpp
    ${core_dir}/src/detail/ripemd_160.cpp
    ${core_dir}/src/detail/set_thread_name.cpp
    ${core_dir}/src/detail/stream_bridge.cpp
    ${core_dir}/src/detail/stringification_inspector.cpp
    ${core_dir}/src/detail/sync_request_bouncer.cpp
    ${core_dir}/src/detail/test_actor_clock.cpp
    ${core_dir}/src/detail/thread_safe_actor_clock.cpp
    ${core_dir}/src/detail/type_id_list_builder.cpp
    ${core_dir}/src/disposable.cpp
    ${core_dir}/src/error.cpp
    ${core_dir}/src/event_based_actor.cpp
    ${core_dir}/src/execution_unit.cpp
    ${core_dir}/src/flow/coordinated.cpp
    ${core_dir}/src/flow/coordinator.cpp
    ${core_dir}/src/flow/observable_builder.cpp
    ${core_dir}/src/flow/op/interval.cpp
    ${core_dir}/src/flow/scoped_coordinator.cpp
    ${core_dir}/src/flow/subscription.cpp
    ${core_dir}/src/forwarding_actor_proxy.cpp
    ${core_dir}/src/group.cpp
    ${core_dir}/src/group_manager.cpp
    ${core_dir}/src/group_module.cpp
    ${core_dir}/src/hash/sha1.cpp
    ${core_dir}/src/init_global_meta_objects.cpp
    ${core_dir}/src/ipv4_address.cpp
    ${core_dir}/src/ipv4_endpoint.cpp
    ${core_dir}/src/ipv4_subnet.cpp
    ${core_dir}/src/ipv6_address.cpp
    ${core_dir}/src/ipv6_endpoint.cpp
    ${core_dir}/src/ipv6_subnet.cpp
    ${core_dir}/src/json_array.cpp
    ${core_dir}/src/json_builder.cpp
    ${core_dir}/src/json_object.cpp
    ${core_dir}/src/json_reader.cpp
    ${core_dir}/src/json_value.cpp
    ${core_dir}/src/json_writer.cpp
    ${core_dir}/src/load_inspector.cpp
    ${core_dir}/src/local_actor.cpp
    ${core_dir}/src/logger.cpp
    ${core_dir}/src/mailbox_element.cpp
    ${core_dir}/src/make_config_option.cpp
    ${core_dir}/src/message.cpp
    ${core_dir}/src/message_builder.cpp
    ${core_dir}/src/message_handler.cpp
    ${core_dir}/src/monitorable_actor.cpp
    ${core_dir}/src/node_id.cpp
    ${core_dir}/src/policy/unprofiled.cpp
    ${core_dir}/src/policy/work_sharing.cpp
    ${core_dir}/src/policy/work_stealing.cpp
    ${core_dir}/src/proxy_registry.cpp
    ${core_dir}/src/raise_error.cpp
    ${core_dir}/src/ref_counted.cpp
    ${core_dir}/src/replies_to.cpp
    ${core_dir}/src/response_promise.cpp
    ${core_dir}/src/resumable.cpp
    ${core_dir}/src/save_inspector.cpp
    ${core_dir}/src/scheduled_actor.cpp
    ${core_dir}/src/scheduler/abstract_coordinator.cpp
    ${core_dir}/src/scheduler/test_coordinator.cpp
    ${core_dir}/src/scoped_actor.cpp
    ${core_dir}/src/scoped_execution_unit.cpp
    ${core_dir}/src/serializer.cpp
    ${core_dir}/src/settings.cpp
    ${core_dir}/src/skip.cpp
    ${core_dir}/src/stream.cpp
    ${core_dir}/src/string_algorithms.cpp
    ${core_dir}/src/string_view.cpp
    ${core_dir}/src/telemetry/collector/prometheus.cpp
    ${core_dir}/src/telemetry/importer/process.cpp
    ${core_dir}/src/telemetry/label.cpp
    ${core_dir}/src/telemetry/label_view.cpp
    ${core_dir}/src/telemetry/metric.cpp
    ${core_dir}/src/telemetry/metric_family.cpp
    ${core_dir}/src/telemetry/metric_registry.cpp
    ${core_dir}/src/term.cpp
    ${core_dir}/src/thread_hook.cpp
    ${core_dir}/src/timestamp.cpp
    ${core_dir}/src/tracing_data.cpp
    ${core_dir}/src/tracing_data_factory.cpp
    ${core_dir}/src/type_id.cpp
    ${core_dir}/src/type_id_list.cpp
    ${core_dir}/src/uri.cpp
    ${core_dir}/src/uri_builder.cpp
    ${core_dir}/src/uuid.cpp
    )

rendu_add_library(
    DIR
    ${core_dir}
    PROJECT
    ${PROJECT_NAME}
    NAME
    caf_core
    HDRS
    ${caf_core_headers}
    SRCS
    ${caf_core_files}
    SETTING
    rendu-dependency-interface
    DEPS
    dep::threads
    LINKOPTS
)

