/*
* Created by boil on 2024/2/18.
*/

#include "socket_error_pal.h"

NET_NAMESPACE_BEGIN

// Initialize the error mappings
std::unordered_map<interop::Error, SocketError> SocketErrorPal::s_native_to_socket_error{
    {interop::Error::RD_EACCES,
     SocketError::AccessDenied},
    {interop::Error::RD_EADDRINUSE,
     SocketError::AddressAlreadyInUse},
    {interop::Error::RD_EADDRNOTAVAIL,
     SocketError::AddressNotAvailable},
    {interop::Error::RD_EAFNOSUPPORT,
     SocketError::AddressFamilyNotSupported},
    {interop::Error::RD_EAGAIN,
     SocketError::WouldBlock},
    {interop::Error::RD_EALREADY,
     SocketError::AlreadyInProgress},
    {interop::Error::RD_EBADF,
     SocketError::OperationAborted},
    {interop::Error::RD_ECANCELED,
     SocketError::OperationAborted},
    {interop::Error::RD_ECONNABORTED,
     SocketError::ConnectionAborted},
    {interop::Error::RD_ECONNREFUSED,
     SocketError::ConnectionRefused},
    {interop::Error::RD_ECONNRESET,
     SocketError::ConnectionReset},
    {interop::Error::RD_EDESTADDRREQ,
     SocketError::DestinationAddressRequired},
    {interop::Error::RD_EFAULT,
     SocketError::Fault},
    {interop::Error::RD_EHOSTDOWN,
     SocketError::HostDown},
    {interop::Error::RD_ENXIO,
     SocketError::HostNotFound},
    {interop::Error::RD_EHOSTUNREACH,
     SocketError::HostUnreachable},
    {interop::Error::RD_EINPROGRESS,
     SocketError::InProgress},
    {interop::Error::RD_EINTR,
     SocketError::Interrupted},
    {interop::Error::RD_EINVAL,
     SocketError::InvalidArgument},
    {interop::Error::RD_EISCONN,
     SocketError::IsConnected},
    {interop::Error::RD_EMFILE,
     SocketError::TooManyOpenSockets},
    {interop::Error::RD_EMSGSIZE,
     SocketError::MessageSize},
    {interop::Error::RD_ENETDOWN,
     SocketError::NetworkDown},
    {interop::Error::RD_ENETRESET,
     SocketError::NetworkReset},
    {interop::Error::RD_ENETUNREACH,
     SocketError::NetworkUnreachable},
    {interop::Error::RD_ENFILE,
     SocketError::TooManyOpenSockets},
    {interop::Error::RD_ENOBUFS,
     SocketError::NoBufferSpaceAvailable},
    {interop::Error::RD_ENODATA,
     SocketError::NoData},
    {interop::Error::RD_ENOENT,
     SocketError::AddressNotAvailable},
    {interop::Error::RD_ENOPROTOOPT,
     SocketError::ProtocolOption},
    {interop::Error::RD_ENOTCONN,
     SocketError::NotConnected},
    {interop::Error::RD_ENOTSOCK,
     SocketError::NotSocket},
    {interop::Error::RD_ENOTSUP,
     SocketError::OperationNotSupported},
    {interop::Error::RD_EPERM,
     SocketError::AccessDenied},
    {interop::Error::RD_EPIPE,
     SocketError::Shutdown},
    {interop::Error::RD_EPFNOSUPPORT,
     SocketError::ProtocolFamilyNotSupported},
    {interop::Error::RD_EPROTONOSUPPORT,
     SocketError::ProtocolNotSupported},
    {interop::Error::RD_EPROTOTYPE,
     SocketError::ProtocolType},
    {interop::Error::RD_ESOCKTNOSUPPORT,
     SocketError::SocketNotSupported},
    {interop::Error::RD_ESHUTDOWN,
     SocketError::Disconnecting},
    {interop::Error::RD_SUCCESS,
     SocketError::Success},
    {interop::Error::RD_ETIMEDOUT,
     SocketError::TimedOut}};

std::unordered_map<SocketError, interop::Error> SocketErrorPal::s_socket_to_native_error{
    {SocketError::AccessDenied,
     interop::Error::RD_EACCES},
    {SocketError::AddressAlreadyInUse,
     interop::Error::RD_EADDRINUSE},
    {SocketError::AddressNotAvailable,
     interop::Error::RD_EADDRNOTAVAIL},
    {SocketError::AddressFamilyNotSupported,
     interop::Error::RD_EAFNOSUPPORT},
    {SocketError::AlreadyInProgress,
     interop::Error::RD_EALREADY},
    {SocketError::ConnectionAborted,
     interop::Error::RD_ECONNABORTED},
    {SocketError::ConnectionRefused,
     interop::Error::RD_ECONNREFUSED},
    {SocketError::ConnectionReset,
     interop::Error::RD_ECONNRESET},
    {SocketError::DestinationAddressRequired,
     interop::Error::RD_EDESTADDRREQ},
    {SocketError::Disconnecting,
     interop::Error::RD_ESHUTDOWN},
    {SocketError::Fault,
     interop::Error::RD_EFAULT},
    {SocketError::HostDown,
     interop::Error::RD_EHOSTDOWN},
    //    {SocketError::HostNotFound,
    //     interop::Error::RD_EHOSTNOTFOUND},
    {SocketError::HostUnreachable,
     interop::Error::RD_EHOSTUNREACH},
    {SocketError::InProgress,
     interop::Error::RD_EINPROGRESS},
    {SocketError::Interrupted,
     interop::Error::RD_EINTR},
    {SocketError::InvalidArgument,
     interop::Error::RD_EINVAL},
    {SocketError::IOPending,
     interop::Error::RD_EINPROGRESS},
    {SocketError::IsConnected,
     interop::Error::RD_EISCONN},
    {SocketError::MessageSize,
     interop::Error::RD_EMSGSIZE},
    {SocketError::NetworkDown,
     interop::Error::RD_ENETDOWN},
    {SocketError::NetworkReset,
     interop::Error::RD_ENETRESET},
    {SocketError::NetworkUnreachable,
     interop::Error::RD_ENETUNREACH},
    {SocketError::NoBufferSpaceAvailable,
     interop::Error::RD_ENOBUFS},
    {SocketError::NoData,
     interop::Error::RD_ENODATA},
    {SocketError::NotConnected,
     interop::Error::RD_ENOTCONN},
    {SocketError::NotSocket,
     interop::Error::RD_ENOTSOCK},
    {SocketError::OperationAborted,
     interop::Error::RD_ECANCELED},
    {SocketError::OperationNotSupported,
     interop::Error::RD_ENOTSUP},
    {SocketError::ProtocolFamilyNotSupported,
     interop::Error::RD_EPFNOSUPPORT},
    {SocketError::ProtocolNotSupported,
     interop::Error::RD_EPROTONOSUPPORT},
    {SocketError::ProtocolOption,
     interop::Error::RD_ENOPROTOOPT},
    {SocketError::ProtocolType,
     interop::Error::RD_EPROTOTYPE},
    {SocketError::Shutdown,
     interop::Error::RD_EPIPE},
    {SocketError::SocketNotSupported,
     interop::Error::RD_ESOCKTNOSUPPORT},
    {SocketError::Success,
     interop::Error::RD_SUCCESS},
    {SocketError::TimedOut,
     interop::Error::RD_ETIMEDOUT},
    {SocketError::TooManyOpenSockets,
     interop::Error::RD_ENFILE},
    {SocketError::TryAgain,
     interop::Error::RD_EAGAIN},
    {SocketError::WouldBlock,
     interop::Error::RD_EAGAIN},
    //    {SocketError::Error,
    //     interop::Error::RD_ESOCKETERROR}
};


std::optional<SocketError> SocketErrorPal::GetSocketErrorForNativeError(interop::Error native_err) {
  auto it = s_native_to_socket_error.find(native_err);
  if (it != s_native_to_socket_error.end()) {
    return it->second;
  }
  return std::nullopt;
}

std::optional<interop::Error> SocketErrorPal::GetNativeErrorForSocketError(SocketError socket_err) {
  auto it = s_socket_to_native_error.find(socket_err);
  if (it != s_socket_to_native_error.end()) {
    return it->second;
  }
  return std::nullopt;
}

NET_NAMESPACE_END