// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/compiler/ruby/ruby_generated_code_proto2_import.proto
// Protobuf C++ Version: 5.28.0-dev

#include "google/protobuf/compiler/ruby/ruby_generated_code_proto2_import.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace A {
namespace B {
namespace C {
              template <typename>
PROTOBUF_CONSTEXPR TestImportedMessage::TestImportedMessage(::_pbi::ConstantInitialized)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()) {}
struct TestImportedMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestImportedMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestImportedMessageDefaultTypeInternal() {}
  union {
    TestImportedMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestImportedMessageDefaultTypeInternal _TestImportedMessage_default_instance_;
}  // namespace C
}  // namespace B
}  // namespace A
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto = nullptr;
const ::uint32_t
    TableStruct_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::A::B::C::TestImportedMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::A::B::C::TestImportedMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::A::B::C::_TestImportedMessage_default_instance_._instance,
};
const char descriptor_table_protodef_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\nEgoogle/protobuf/compiler/ruby/ruby_gen"
    "erated_code_proto2_import.proto\022\005A.B.C\"\025"
    "\n\023TestImportedMessage"
};
static ::absl::once_flag descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto = {
    false,
    false,
    101,
    descriptor_table_protodef_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto,
    "google/protobuf/compiler/ruby/ruby_generated_code_proto2_import.proto",
    &descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto::offsets,
    file_level_enum_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto,
    file_level_service_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto,
};
namespace A {
namespace B {
namespace C {
// ===================================================================

class TestImportedMessage::_Internal {
 public:
};

TestImportedMessage::TestImportedMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
  // @@protoc_insertion_point(arena_constructor:A.B.C.TestImportedMessage)
}
TestImportedMessage::TestImportedMessage(
    ::google::protobuf::Arena* arena,
    const TestImportedMessage& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
  TestImportedMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:A.B.C.TestImportedMessage)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    TestImportedMessage::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &TestImportedMessage::MergeImpl,
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<TestImportedMessage>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<TestImportedMessage>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<TestImportedMessage>(),
                ::google::protobuf::internal::ZeroFieldsBase::GetByteSizeLongImpl<TestImportedMessage>(),
                ::google::protobuf::internal::ZeroFieldsBase::GetSerializeImpl<TestImportedMessage>(),
            PROTOBUF_FIELD_OFFSET(TestImportedMessage, _impl_._cached_size_),
            false,
        },
        &TestImportedMessage::kDescriptorMethods,
        &descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* TestImportedMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> TestImportedMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_TestImportedMessage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::A::B::C::TestImportedMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata TestImportedMessage::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace C
}  // namespace B
}  // namespace A
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fcode_5fproto2_5fimport_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
