// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.proto

#include "google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace one {
namespace two {
namespace a_three {
namespace and {
PROTOBUF_CONSTEXPR Four::Four(
    ::_pbi::ConstantInitialized)
  : another_string_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}){}
struct FourDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FourDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FourDefaultTypeInternal() {}
  union {
    Four _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FourDefaultTypeInternal _Four_default_instance_;
}  // namespace and
}  // namespace a_three
}  // namespace two
}  // namespace one
static ::_pb::Metadata file_level_metadata_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto = nullptr;

const uint32_t TableStruct_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::one::two::a_three::and::Four, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::one::two::a_three::and::Four, another_string_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::one::two::a_three::and::Four)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::one::two::a_three::and::_Four_default_instance_._instance,
};

const char descriptor_table_protodef_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\nFgoogle/protobuf/compiler/ruby/ruby_gen"
  "erated_pkg_explicit_legacy.proto\022\023one.tw"
  "o.a_three.and\"\036\n\004Four\022\026\n\016another_string\030"
  "\001 \001(\tB\013\352\002\010AA.BB.CCb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto = {
    false, false, 146, descriptor_table_protodef_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto,
    "google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.proto",
    &descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto::offsets,
    file_level_metadata_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto, file_level_enum_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto,
    file_level_service_descriptors_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto_getter() {
  return &descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto(&descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto);
namespace one {
namespace two {
namespace a_three {
namespace and {

// ===================================================================

class Four::_Internal {
 public:
};

Four::Four(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:one.two.a_three.and.Four)
}
Four::Four(const Four& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  another_string_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    another_string_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_another_string().empty()) {
    another_string_.Set(from._internal_another_string(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:one.two.a_three.and.Four)
}

inline void Four::SharedCtor() {
another_string_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  another_string_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Four::~Four() {
  // @@protoc_insertion_point(destructor:one.two.a_three.and.Four)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Four::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  another_string_.Destroy();
}

void Four::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Four::Clear() {
// @@protoc_insertion_point(message_clear_start:one.two.a_three.and.Four)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  another_string_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Four::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string another_string = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_another_string();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "one.two.a_three.and.Four.another_string"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Four::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:one.two.a_three.and.Four)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string another_string = 1;
  if (!this->_internal_another_string().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_another_string().data(), static_cast<int>(this->_internal_another_string().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "one.two.a_three.and.Four.another_string");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_another_string(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:one.two.a_three.and.Four)
  return target;
}

size_t Four::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:one.two.a_three.and.Four)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string another_string = 1;
  if (!this->_internal_another_string().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_another_string());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Four::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Four::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Four::GetClassData() const { return &_class_data_; }

void Four::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Four *>(to)->MergeFrom(
      static_cast<const Four &>(from));
}


void Four::MergeFrom(const Four& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:one.two.a_three.and.Four)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_another_string().empty()) {
    _internal_set_another_string(from._internal_another_string());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Four::CopyFrom(const Four& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:one.two.a_three.and.Four)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Four::IsInitialized() const {
  return true;
}

void Four::InternalSwap(Four* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &another_string_, lhs_arena,
      &other->another_string_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Four::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto_getter, &descriptor_table_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto_once,
      file_level_metadata_google_2fprotobuf_2fcompiler_2fruby_2fruby_5fgenerated_5fpkg_5fexplicit_5flegacy_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace and
}  // namespace a_three
}  // namespace two
}  // namespace one
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::one::two::a_three::and::Four*
Arena::CreateMaybeMessage< ::one::two::a_three::and::Four >(Arena* arena) {
  return Arena::CreateMessageInternal< ::one::two::a_three::and::Four >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
